### ISSUE TITLE
Dynamo tables created in wrong region.

### ISSUE THREAD

**Issue by jolcese** [awslabs/amazon-kinesis-aggregators#12]
I have an EC2 instance running an aggregator app. It reads fine from a Kinesis Stream but the aggregated tables are generated in an incorrect region.
How do I specify the region of the DynamoDB tables?

BTW, the KCL app is creating tables in the right region.

**Comment by IanMeyers** [comment]
Hello,

Which region have you set on the Aggregator process? And also which region is the stream in, vs where the KCL Lease Table is being created?

Thx,

Ian

**Comment by jolcese** [comment]
Hi Ian,
Ec2, Stream and lease tables are on us-west-2.
Where do I specify the region for the agreggator process?
Thanks
Jose

**Comment by IanMeyers** [comment]
You can use the 'region' system property. Set -Dregion=us-west-2 from the command line.

**Comment by jolcese** [comment]
Thanks Ian,
Any way to pass that parameter thru configuration files?

**Comment by IanMeyers** [comment]
Yeah, this should be doable. I will add this to the backlog. How are you running the application today?

**Comment by jolcese** [comment]
I have a Chef script that deploys the application on EC2s on an autoscaling group.
Chef writes the configuration file based on a template which gets as inputs the table names, provisioned capacity, etc.

Something like this:
```[{
    "namespace": "<%= @table_prefix %>_timeseries_aggregation_events_app",
    "timeHorizons": [
        "HOUR",
        "DAY",
        "MONTH",
        "YEAR",
        "FOREVER"
    ],
    "type": "SUM",
    "dataExtractor": "JSON",
    "labelItems": [
        "deviceEventKey"
    ],
    "dateItem": "timestamp",
    "dateFormat": "yyyy-MM-dd'T'HH:mm:ss'Z'",
    "summaryItems": [
        "sum(value.attr0) sum-attr0",
        "min(value.attr0) min-attr0",
        "max(value.attr0) max-attr0",
      ],
    "tableName": "<%= @table_prefix %>_timeseries_aggregated_event",
    "readIOPS": <%= @read_iops %>,
    "writeIOPS": <%= @write_iops %>
}]```

**Comment by IanMeyers** [comment]
OK - that's quite nice. How does Chef then run the process, if at all? Or is an init.d or similar being used to run the aggregator process?

**Comment by IanMeyers** [comment]
Closing now and will open a feature req
