### ISSUE TITLE
FOREVER timeHorizon seems to set dateValue to * and issues this error... 

### ISSUE THREAD

**Issue by DeadZen** [awslabs/amazon-kinesis-aggregators#6]
17-Jun-2015 20:19:15.970 SEVERE [pool-1-thread-1] com.amazonaws.services.kinesis.aggregators.cache.AggregateCache.flush Metrics Emitter Exception - Aggregate Cache will NOT terminate
17-Jun-2015 20:19:15.970 SEVERE [pool-1-thread-1] com.amazonaws.services.kinesis.aggregators.cache.AggregateCache.flush java.text.ParseException: Unparseable date: "*"

**Comment by IanMeyers** [comment]
Hello,

Yes, Apologies for this. Let me issue a patch.

Ian

**Comment by IanMeyers** [comment]
Request for an opinion - when you use TimeHorizon.FOREVER, the Emitted CloudWatch metrics would only ever be for a single date value. This isn't a very meaningful timeseries, so there are two sensible options. The first would be to NOT emit metrics for this TimeHorizon, or alternatively we can emit metrics but use the current date/time as the date of the metric. This would mean you would see the values in CloudWatch, but they would NOT match what was in the timeseries table.

Thoughts?

**Comment by IanMeyers** [comment]
Fixed in .9.2.6.9. Will leave the issue open so that you can comment on the above.

**Comment by DeadZen** [comment]
I see now, suppose you could always opt to disable it manually for that
time series with emitMetrics=false on the user side, maybe issuing a
warning about it so the user can decide which action to take. For instance
not emitting and issuing a warning about it (once?) would indicate to the
user they did nothing wrong and the total aggregate still works its just
not a useful time series for cloudwatch so turn emit metrics off to make
the warning go away. If the alternative is useful but not accurate, That
could be communicated in the warning, and if its not acceptable the user
could just disable as the only alternative would be to disable it anyway. I
think the main source of confusion for the user is not understanding what
layer of the software is reporting that error.

**Comment by IanMeyers** [comment]
Understood. So in .9.2.6.9 the error will no longer occur, and the metric will NOT be pushed to CloudWatch.

**Comment by DeadZen** [comment]
Verified fixed
